name: Github Actions CI to build pdf from tex source.
on: push

permissions: write-all

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
          # The root LaTeX file to be compiled
          root_file: CV.tex

          # Interpret the root_file input as bash glob pattern
          # glob_root_file: # optional

          # The working directory for this action
          # working_directory: # optional

          # The LaTeX engine to be invoked
          # compiler: # optional, default is latexmk

          # Extra arguments to be passed to the LaTeX engine
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

          # Install extra packages by apk
          # extra_system_packages: # optional

          # Install extra .ttf/.otf fonts.
          # extra_fonts: ./fonts/*.ttf

          # Arbitrary bash codes to be executed before compiling LaTeX documents
          pre_compile: tlmgr update --self && tlmgr update --all

          # Arbitrary bash codes to be executed after compiling LaTeX documents
          post_compile: latexmk -c

          # Instruct latexmk to enable --shell-escape
          # latexmk_shell_escape: # optional

          # Instruct latexmk to use LuaLaTeX
          # latexmk_use_lualatex: # optional

          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true 

    - name: Check pdf file
      run: |
        file CV.pdf | grep -q ' PDF '

    - name: Upload file to repository
      run: |
        git config --global user.name "DustinMlong"
        git config --global user.email "dustinlong318@gmail.com"
        git add CV.pdf
        git commit -m "commit message"
        git push
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    - name: Push generated webpage to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.3
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
          source-files: 'CV.pdf'
          destination-username: 'DustinMLong'
          destination-repository: 'dustinmlong'
          destination-directory: 'files'
          commit-email: 'dustinlong318@gmail.com'
